import React, {Component} from 'react';
import {Text, ScrollView} from 'react-native';
import AppBackground from '../../../components/AppBackground';
import {Colors} from '../../../config';

export class EventPrivacyPolicy extends Component {
  render() {
    return (
      <AppBackground title={'Privacy Policy'} profile={false} notification={false} back>
        <ScrollView
          showsVerticalScrollIndicator={false}
          style={{flex: 1}}
          contentContainerStyle={{flexGrow: 1, paddingTop: 15}}>
          <Text>
<Text style={{fontSize:22,color:Colors.white,fontWeight:'bold'}}>{'\n'}Privacy Policy{'\n'}</Text>
<Text style={{color:Colors.white}}>{'\n'}By accessing and placing an order with Outsideee, you confirm that you are in agreement with and bound by the terms of

Outsideee ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Outsideee.
This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Outsideee. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
Definitions and key terms
To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
Company: when this policy mentions "Company," "we," "us," or "our," it refers to Outsideee, 6135 Park South Drive Ste 510 Charlotte, NC 28210 that is responsible for your information under this Privacy Policy.
Country: where Outsideee or the owners/founders of Outsideee are based, in this case is United States
• Customer: refers to the company, organization or person that signs up to use the Outsideee Service to manage the relationships with your consumers or service users.
• Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Outsideee and use the services.
• IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address.
These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
• Personnel: refers to those individuals who are employed by Outsideee or are under contract to perform a service on behalf of one of the parties.
• Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number - allows for the identification or identifiability of a natural person.
⚫ Service: refers to the service provided by Outsideee as described in the relative terms (if available) and on this platform. Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
You: a person or entity that is registered with Outsideee to use the Services.
What Information Do We Collect?
We collect information from you when you visit our app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
Name / Username • Phone Numbers
• Email Addresses • Password
We also collect information from mobile devices for a better user experience, although these features are completely optional:
• Location (GPS): Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.{'\n'}</Text>

<Text style={{fontSize:22,color:Colors.white,fontWeight:'bold'}}>{'\n'}License{'\n'}</Text>
<Text style={{color:Colors.white}}>{'\n'}Outsideee grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the app strictly in
accordance with the terms of this Agreement.
These Terms & Conditions are a contract between you and Outsideee (referred to in these Terms & Conditions as "Outsideee",
"us", "we" or "our"), the provider of the Outsideee website and the services accessible from the Outsideee website (which are
collectively referred to in these Terms & Conditions as the "Outsideee Service").
You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use
the Outsideee Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If
you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account
without notice.{'\n'}</Text>
<Text style={{fontSize:22,color:Colors.white,fontWeight:'bold'}}>{'\n'}Definitions and key terms{'\n'}</Text>
<Text style={{color:Colors.white}}>{'\n'}To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are
strictly defined as:
● Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
provide analytics, remember information about you such as your language preference or login information.
● Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Outsideee LLC, 6135 Park South Drive Ste
510 Charlotte, NC 28210 that is responsible for your information under this Terms & Conditions.
● Country: where Outsideee or the owners/founders of Outsideee are based, in this case is United States
● Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit
Outsideee and use the services.
● Service: refers to the service provided by Outsideee as described in the relative terms (if available) and on this platform.
● Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide
our content or whose products or services we think may interest you.
● Website: Outsideee."’s" site, which can be accessed via this URL:
● You: a person or entity that is registered with Outsideee to use the Services.{'\n'}</Text>
<Text style={{fontSize:22,color:Colors.white,fontWeight:'bold'}}>{'\n'}Restrictions{'\n'}</Text>
<Text style={{color:Colors.white}}>{'\n'}You agree not to, and you will not permit others to:
● License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the app or
make the platform available to any third party.
● Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the app.
● Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Outsideee or its
affiliates, partners, suppliers or the licensors of the app.{'\n'}</Text>
<Text style={{fontSize:22,color:Colors.white,fontWeight:'bold'}}>{'\n'}Return and Refund Policy{'\n'}</Text>
<Text style={{color:Colors.white}}>{'\n'}Thanks for shopping at Outsideee. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you

<Text style={{fontSize:22,color:Colors.white,fontWeight:'bold'}}>{'\n'}Contact Us{'\n'}</Text>
{'\n'}
Don't hesitate to contact us if you have any questions.{'\n'}</Text>
● Via Email: outsideeeapp@gmail.com
          </Text>
        </ScrollView>
      </AppBackground>
    );
  }
}

export default EventPrivacyPolicy;
